In [1]:
import tensorflow as tf

In [2]:
A = tf.constant(1)
print(A)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
B = tf.constant(1.0)
print(B)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [4]:
C = tf.constant(1.)
print(C)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [5]:
D = tf.constant(1, dtype=tf.float32)
print(D)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [9]:
# Throws an error because A is not the same type as B.
# E = tf.math.add(A, B)

# Solution
E = tf.math.add(tf.cast(A, dtype=tf.float32), B)
print(E)

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]

In [ ]:
# Throws an error because A is not the same type as B.
# E = A + B

# Solution
E = tf.cast(A, dtype=tf.float32) + B